apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: clock-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clock
  template:
    metadata:
      labels:
        app: clock
    spec:
      containers:
      - name: clock
        image: clock:v2.1
        envFrom:
          - configMapRef:
              name: clock
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 3000
            path: /healthz
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: clock-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: clock
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: clock
data:
  PORT: "3000"
  HOST: "0.0.0.0"
